---
# yaml-language-server: $schema=https://raw.githubusercontent.com/pamburus/hl/master/schema/json/config.schema.json
$schema: https://raw.githubusercontent.com/pamburus/hl/master/schema/json/config.schema.json

# Time format, see https://man7.org/linux/man-pages/man1/date.1.html for details.
time-format: '%b %d %T.%3N'

# Time zone name, see column "TZ identifier" at
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones page.
time-zone: Europe/Moscow
# Settings for fields processing.
fields:
  # Configuration of the predefined set of fields.
  predefined:
    time:
      show: auto
      names: [Timestamp]
    level:
      show: auto
      variants:
        - names: [Severity]
          values:
            debug: [1, 2, 3, 4, 5, 6, 7, 8]
            info: [9, 10, 11, 12]
            warning: [13, 14, 15, 16]
            error: [17, 18, 19, 20, 21, 22, 23, 24]
    message:
      names: [Body.Value]
  # List of wildcard field names to ignore.
  ignore: [_*]
  # List of exact field names to hide.
  hide:
    - ObservedTimestamp
    - Body
    - Scope
    - DroppedAttributes
    - SeverityText
    - Resource
    - TraceFlags
# Formatting settings.
formatting:
  flatten: always
  punctuation:
    logger-name-separator: ':'
    field-key-value-separator: '='
    string-opening-quote: "'"
    string-closing-quote: "'"
    source-location-separator: '→ '
    hidden-fields-indicator: ' ...'
    level-left-separator: │
    level-right-separator: │
    input-number-prefix: '#'
    input-number-left-separator: ''
    input-number-right-separator: ' │ '
    input-name-left-separator: ''
    input-name-right-separator: ' │ '
    input-name-clipping: ··
    input-name-common-part: ··
    array-separator: ' '
# Number of processing threads, configured automatically based on CPU count if not specified.
concurrency:
# Currently selected theme.
theme: universal
