---
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports: [5432:5432]
    volumes: [pg-data:/var/lib/postgresql/data]
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports: [16686:16686, '14268', '14250']
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [--config=/etc/otel-collector-config.yaml, '${OTELCOL_ARGS}']
    volumes: [./configs/otel-collector.yaml:/etc/otel-collector-config.yaml]
    ports:
      - 8888:8888  # Prometheus metrics exposed by the collector
      - 8889:8889  # Prometheus exporter metrics
      - 4317:4317  # OTLP gRPC receiver
      - 4318:4318  # OTLP HTTP receiver
      - 1888:1888  # pprof extension
      - 13133:13133  # health_check extension
      - 55679:55679  # zpages extension
    depends_on: [jaeger]
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes: [./configs/prometheus.yaml:/etc/prometheus/prometheus.yml]
    ports: [9090:9090]
volumes:
  pg-data:
  grafana-data:
